# webserver setup playbook
---
  - hosts: Webservers
    become: true
    tasks:
      - name: create new file
        lineinfile: 
          create: yes
          path: /var/www/html/index.html
          line: <html>Hell from server1<html>
        notify: start apache
      
    handlers:
      - name: start apache
        service: name=apache2 state=started